-- ─────────────────────────────────────────────────────────────────────────────
-- WP-LS1 — "Lead Source 1" becomes the only ingestable format + MLS rules v2.
-- Owner decisions 2026-07-15. Spec: docs/superpowers/specs/2026-07-15-wp-ls1-lead-source-1.md
--
-- DM-08 note: historical runs do NOT read these tables — every run replays from the
-- rules_snapshot pinned on its upload row. That is what makes retiring the live rule
-- set safe. No snapshot needs an explicit "bump": the snapshot hash is derived from
-- the live rules at run time, so changing the rows below changes it automatically.
--
-- Idempotent below the generated ALTER: ON CONFLICT DO NOTHING + guarded DELETE.
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. The transform seam (SEAM; generated by drizzle-kit from schema.ts).
--    Detection prefers SAVED profile rows over the code seeds, so the transform name
--    must persist — a row that loses it would silently ingest leads with no address,
--    no seller name, and un-stripped skip-trace notes (SEC-05). Proven by
--    tests/integration/lead-source-1-profile.test.ts. Nullable: profiles needing no
--    derivation leave it NULL.
ALTER TABLE "source_profiles" ADD COLUMN "transform" text;
--> statement-breakpoint

-- 2. Retire the v1 MLS pattern set. `enabled` is this table's designed lifecycle
--    column and loadRunRules filters on it; the regex TEXT of a v1 row is never
--    altered, so nothing about the historical rule set is destroyed or rewritten.
--    The bare `on market` pattern this disables was false-firing on the
--    "MLS History / Days on Market:" template label in 57% of vendor-A rows.
UPDATE "mls_patterns" SET "enabled" = false WHERE "pattern_key" NOT LIKE 'dq\_ls1\_%';
--> statement-breakpoint

-- 3. Seed the v2 disqualifiers for every tenant.
--    THE RULE: a lead is removed ONLY when a structured listing question is answered
--    Yes/Y/True. No keep-overrides — No/blank falls through to the engine's default
--    keep (MLS-03), which IS the owner rule. Verified on 182 real rows: 112/70.
--    ⚠️ [ \t]* and never \s* — the notes are multiline and \s crosses newlines, which
--    would bind a question to an answer on a different line (PRN-04).
INSERT INTO "mls_patterns" ("tenant_id", "pattern_key", "type", "regex", "flags", "label", "enabled")
SELECT t."id", v."pattern_key", v."type"::"pattern_type", v."regex", v."flags", v."label", true
FROM "tenants" t
CROSS JOIN (VALUES
  ('dq_ls1_is_it_listed_yes',   'disqualify', 'is[ \t]+it[ \t]+listed[ \t]*\??[ \t]*:?[ \t]*(?:yes|y|true)\b',        'i',  'is it listed? : yes/y/true'),
  ('dq_ls1_listed_mls_yes',     'disqualify', 'listed[ \t]+on[ \t]+mls[ \t]*\??[ \t]*:?[ \t]*(?:yes|y|true)\b',       'i',  'listed on mls? yes'),
  ('dq_ls1_listed_realtor_yes', 'disqualify', 'listed[ \t]+with[ \t]+realtor[ \t]*\??[ \t]*:?[ \t]*(?:yes|y|true)\b', 'i',  'listed with realtor? yes'),
  -- Line-anchored (^ + the m flag): "listed?" is a substring of "Listed with realtor?"
  -- and "Listed on MLS?", so without the anchor this would fire on every vendor-B row.
  ('dq_ls1_listed_yes',         'disqualify', '^[ \t]*\*?[ \t]*listed[ \t]*\?[ \t]*:?[ \t]*(?:yes|y|true)\b',         'im', 'listed? yes')
) AS v("pattern_key", "type", "regex", "flags", "label")
-- CONVERGENT, not merely idempotent: re-running must GUARANTEE the v2 set is live and
-- correct, including re-enabling a row that a partial/aborted run left disabled or stale.
-- DO NOTHING would report success while leaving a disabled dq_ls1_listed_yes in place —
-- i.e. silently under-removing, shipping listed leads to partners. The v1 rows' regex text
-- is still never altered (DM-08); these four keys only ever exist as v2.
ON CONFLICT ("tenant_id", "pattern_key") DO UPDATE SET
  "type" = EXCLUDED."type",
  "regex" = EXCLUDED."regex",
  "flags" = EXCLUDED."flags",
  "label" = EXCLUDED."label",
  "enabled" = true;
--> statement-breakpoint

-- 4. The Lead Source 1 profile is deliberately NOT inserted as a row here.
--    It ships as a CODE seed (src/modules/sources/seed-profiles.ts) and
--    loadProfilesForDetection already unions the seeds for any format not yet saved,
--    so detection picks it up with no row at all. Inserting one would mean restating
--    the 179-column signature in SQL — duplicated, and worse: saved rows SHADOW the
--    code seed by name, so any drift between the two would silently win over the code.
--    A row is created the first time an admin confirms a version (ING-08), which is the
--    only moment the DB legitimately owns a profile's shape.

-- 5. Remove the retired profile ROWS (owner decision 2026-07-15: delete, not deactivate).
--    GUARDED: uploads.source_profile_id is a FK with ON DELETE NO ACTION, so a profile any
--    upload references cannot be deleted — the DELETE would abort this migration rather
--    than destroy real history (DM-08).
--    ⚠️ Be honest about how much that guard is currently worth: NO code path writes
--    uploads.source_profile_id today (persistRun never sets it — see the WP candidate to
--    wire it), so the column is empty everywhere and this guard is a defensive no-op, not
--    a verified protection of live history. It costs nothing and starts doing real work
--    the moment the column is wired. Profile provenance for past runs currently lives in
--    uploads.rules_snapshot ({sourceProfile:{id,version}}), which is what actually makes
--    deleting these rows safe — the snapshot survives the delete.
--    Verified on dev: one row (Generic v1), zero uploads referencing it.
DELETE FROM "source_profiles" sp
WHERE sp."name" IN ('Generic', 'InvestorFuse')
  AND NOT EXISTS (
    SELECT 1 FROM "uploads" u WHERE u."source_profile_id" = sp."id"
  );
