// Label anchors for the CountyCoverageMap state-label layer (WP-UX-4 / MAP-06), expressed in
// the viewBox space of public/geo/us-counties.json ("0 0 960 600") — the same coordinate
// space the county paths are pre-projected into, so an anchor stays glued to its state under
// the map's zoom/pan transform. Keys are USPS codes: exactly the value set of
// STATE_FIPS_TO_CODE (50 states + DC), so the table stays in lockstep with the geometry the
// same way the FIPS table does.
//
// This is DATA (PRN-10): committed constants, never derived at runtime, never executed.
// Generated offline, then hand-tuned — see Provenance below.
//
// ── Provenance & verification (2026-08-18) ──────────────────────────────────────────────
// Generated by a throwaway Node script (not committed; ADR-0050, and the generator's
// implementation is explicitly out of scope of the WP-UX-4 spec) that:
//   1. Parses every county path `d` in public/geo/us-counties.json and groups the counties by
//      FIPS prefix via src/lib/geo/us-state-fips.ts.
//   2. Scanline-rasterizes each state's counties into a 1-unit mask over the 960×600 viewBox
//      and takes the "pole of inaccessibility" — the interior cell farthest from the state
//      outline, via a two-pass chamfer distance transform. This is INSIDE the state by
//      construction, which a coordinate mean or bbox center is not: the mean puts CA in the
//      Pacific-facing coastal vertices, the bbox center puts FL in the Gulf, MI in Lake
//      Michigan and ID in the panhandle.
//   3. De-collides the result: no two anchors' WORST-CASE chips (8 characters, "MM · 999" →
//      LABEL_CHIP_WIDTH_MAX × LABEL_CHIP_HEIGHT) may overlap at s = 1, and no worst-case chip
//      may clip the viewBox edge. Each anchor may only move to another point inside its own
//      state, nearest-to-pole first, most-constrained state first. Six states moved, by
//      3–19 units: ME, VA, OH, AL, IL, GA, OK.
//
// Verified on the generated table (mirrored by tests/unit/geo/us-state-anchors.test.ts):
//   - 51 keys, identical to the STATE_FIPS_TO_CODE value set.
//   - Every anchor and leader point strictly inside 0 0 960 600.
//   - Every non-callout anchor lies inside its own state's rasterized footprint (HI is the one
//     documented exception — see the hand-tunes below).
//   - No two worst-case chips overlap; no worst-case chip clips the viewBox.
//
// ── Hand-tunes ──────────────────────────────────────────────────────────────────────────
//   - HI  — placed just BELOW the island chain rather than on it. The generated pole lands on
//           the Big Island, where a 59-wide chip would bury the only island large enough to
//           read. This is the single anchor deliberately outside its own footprint, and it
//           takes no leader (spec §10 #6 default).
//   - CT, DC, DE, MA, MD, NH, NJ, RI, VT — the nine seaboard states too small to hold a chip
//           get CALLOUT anchors: a fixed column over the Atlantic at x = 918, stacked north→
//           south in the order VT, NH, MA, RI, CT, NJ, DE, MD, DC with 26 units of vertical
//           spacing (≥ 24 required so worst-case chips can never touch at s = 1). Each keeps a
//           `leader` at its own interior pole. The column starts at y = 228 — below Long
//           Island's easternmost reach (y ≈ 216) — and its worst-case chips span x 879.8–956.2,
//           inside the viewBox with room to spare; the ≤1px graze of NJ's coast (x ≤ 880.7)
//           is harmless — the chip is opaque, and in-place chips sit on land by design. Being a static table
//           makes the stack deterministic: no runtime collision solver, ever.
//   - FL, LA, MI, ID, OK and every other state whose naive center falls outside its own
//           boundary need no manual value — step 2 above already resolves them (FL lands on
//           the peninsula midline, LA west of the delta, MI on the Lower Peninsula).

/** Geometry of one label chip, in viewBox units. IBM Plex Mono is fixed-advance (0.6em), so at
 *  13px the width is a pure function of the character count — no DOM measurement, SSR-safe,
 *  deterministic. Lives here because the anchor table's non-overlap invariant is stated in
 *  terms of it (PRN-15: one home for the number). */
export const LABEL_CHIP_HEIGHT = 20;
/** Worst-case label ("MM · 999", 8 characters) — the footprint the anchor table is spaced for. */
export const LABEL_CHIP_WIDTH_MAX = 76.4;
/** Chip width for a label of `text`: 0.6em × 13px per character + padding. The padding carries
 *  a +2px safety margin (review F-2): 7.8px/char assumes IBM Plex Mono's exact 0.6em advance,
 *  and during the next/font display:swap window a fallback mono face's metrics are close but
 *  not guaranteed identical — the margin keeps the text on the opaque chip even then. */
export function labelChipWidth(text: string): number {
  return 7.8 * text.length + 14;
}

/** The one " · " the page's label text and the chip's tone-splitting share (review F-4):
 *  each side importing this constant is what keeps splitStateLabel finding the separator
 *  the page actually wrote. */
export const LABEL_SEPARATOR = " · ";

export interface StateLabelAnchor {
  /** Chip center. */
  x: number;
  y: number;
  /** Present ⇒ callout state: a leader line is drawn from this interior point to (x, y); the
   *  chip is centered on (x, y) and covers the line's terminus, so zoom counter-scaling can
   *  never open a gap between the two. Absent ⇒ in-place chip. */
  leader?: { x: number; y: number };
}

export const STATE_LABEL_ANCHORS: Readonly<Record<string, StateLabelAnchor>> = {
  AK: { x: 154.5, y: 489.5 },
  AL: { x: 693.5, y: 434.5 },
  AR: { x: 590.5, y: 375.5 },
  AZ: { x: 249.5, y: 376.5 },
  CA: { x: 134.5, y: 306.5 },
  CO: { x: 353.5, y: 279.5 },
  CT: { x: 918, y: 332, leader: { x: 893.5, y: 186.5 } },
  DC: { x: 918, y: 436, leader: { x: 837.5, y: 259.5 } },
  DE: { x: 918, y: 384, leader: { x: 864.5, y: 259.5 } },
  FL: { x: 803.5, y: 513.5 },
  GA: { x: 757.5, y: 414.5 },
  HI: { x: 332, y: 578 },
  IA: { x: 554.5, y: 222.5 },
  ID: { x: 236.5, y: 160.5 },
  IL: { x: 632.5, y: 238.5 },
  IN: { x: 685.5, y: 258.5 },
  KS: { x: 457.5, y: 298.5 },
  KY: { x: 719.5, y: 304.5 },
  LA: { x: 587.5, y: 441.5 },
  MA: { x: 918, y: 280, leader: { x: 904.5, y: 167.5 } },
  MD: { x: 918, y: 410, leader: { x: 835.5, y: 250.5 } },
  ME: { x: 921, y: 93.5 },
  MI: { x: 702.5, y: 195.5 },
  MN: { x: 549.5, y: 115.5 },
  MO: { x: 584.5, y: 304.5 },
  MS: { x: 637.5, y: 414.5 },
  MT: { x: 301.5, y: 98.5 },
  NC: { x: 829.5, y: 339.5 },
  ND: { x: 440.5, y: 103.5 },
  NE: { x: 456.5, y: 233.5 },
  NH: { x: 918, y: 254, leader: { x: 900.5, y: 148.5 } },
  NJ: { x: 918, y: 358, leader: { x: 871.5, y: 234.5 } },
  NM: { x: 349.5, y: 375.5 },
  NV: { x: 186.5, y: 233.5 },
  NY: { x: 852.5, y: 164.5 },
  OH: { x: 736.5, y: 238.5 },
  OK: { x: 511.5, y: 366.5 },
  OR: { x: 159.5, y: 137.5 },
  PA: { x: 832.5, y: 217.5 },
  RI: { x: 918, y: 306, leader: { x: 909.5, y: 178.5 } },
  SC: { x: 798.5, y: 380.5 },
  SD: { x: 434.5, y: 167.5 },
  TN: { x: 708.5, y: 347.5 },
  TX: { x: 487.5, y: 463.5 },
  UT: { x: 270.5, y: 262.5 },
  VA: { x: 821.5, y: 298.5 },
  VT: { x: 918, y: 228, leader: { x: 879.5, y: 125.5 } },
  WA: { x: 177.5, y: 62.5 },
  WI: { x: 617.5, y: 158.5 },
  WV: { x: 776.5, y: 278.5 },
  WY: { x: 335.5, y: 190.5 },
};
